### ISSUE TITLE
Issue with blur and spread values in the "Box Shadow Generator for TailwindCSS" section

### ISSUE THREAD

**Issue by Michaeloye** [manuarora700/manuarora.in#7]
Hello @manuarora700 I'll really like to contribute to this project, I noticed a bug in the boxShadows page, specifically the **Box Shadow Generator for TailwindCSS** section the correction spread value inputted is applied to the element but the element by the right of the spread input, that indicates the spread value seems to be display the value of the blur instead of the spread value

In the below screenshot you'll observe that although the spread value is 11px but the element by the right shows "9px spread" where 9px is the value of the blur
![spread issue](https://github.com/manuarora700/manuarora.in/assets/59027324/057e2913-b0bd-4670-be83-20fe01dc6741)

**Comment by Michaeloye** [comment]
@manuarora700  I've made a PR to resolve this issue, please kindly review (https://github.com/manuarora700/manuarora.in/pull/8)

**Comment by manuarora700** [comment]
Merged, thanks! :)
